server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${APPLICATION_DB_URL:localhost}:${APPLICATION_DB_PORT:5432}/${APPLICATION_DB_NAME:auction}
    username: ${APPLICATION_DB_USER:postgres}
    password: ${APPLICATION_DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    openInView: false
    show_sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true
  flyway:
    user: ${APPLICATION_DB_USER:postgres}
    password: ${APPLICATION_DB_PASSWORD:admin}
    schemas: public
    baselineOnMigrate: true
    url: jdbc:postgresql://${APPLICATION_DB_URL:localhost}:${APPLICATION_DB_PORT:5432}/${APPLICATION_DB_NAME:auction}
    locations: filesystem:src/main/resources/db/migration
    
# swagger host property
host: "bidba-api.herokuapp.com"

stripe:
  apiKey: ${STRIPE_API_KEY:sk_test_51KKK3gHfG2ohyeRDiBA53JiIi4x5m8ijb0tBMbvQtVXUI2EXg5KSIT8BM5cwlgxPBeufRRS8EGHM3Z1Wj9XlEZa800qRoayin4}
